export const ADD_WEEK_PLANNING_LOADING = 'ADD_WEEK_PLANNING_LOADING'
export const ADD_WEEK_PLANNING_SUCCESS = 'ADD_WEEK_PLANNING_SUCCESS'
export const ADD_WEEK_PLANNING_ERROR = 'ADD_WEEK_PLANNING_ERROR'
