name: DB Migrations

on:
  push:
    branches: [ master ]

jobs:
  db-migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Run migrations
        run: yarn db:migrations
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          CONTENTFUL_MIGRATION_ENVIRONMENT: ${{ secrets.CONTENTFUL_MIGRATION_ENVIRONMENT }}
