name: DB Migrations

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  db-migrations:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Run migrations
        run: yarn db:migrations
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          CONTENTFUL_MIGRATION_ENVIRONMENT: ${{ secrets.CONTENTFUL_MIGRATION_ENVIRONMENT }}
